# Numpy

<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Why-numpy" data-toc-modified-id="Why-numpy-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Why numpy</a></span></li><li><span><a href="#Creating-arrays" data-toc-modified-id="Creating-arrays-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Creating arrays</a></span><ul class="toc-item"><li><span><a href="#Custom" data-toc-modified-id="Custom-2.1"><span class="toc-item-num">2.1&nbsp;&nbsp;</span>Custom</a></span><ul class="toc-item"><li><span><a href="#1-dimensional" data-toc-modified-id="1-dimensional-2.1.1"><span class="toc-item-num">2.1.1&nbsp;&nbsp;</span>1 dimensional</a></span></li><li><span><a href="#2-dimensional" data-toc-modified-id="2-dimensional-2.1.2"><span class="toc-item-num">2.1.2&nbsp;&nbsp;</span>2 dimensional</a></span></li><li><span><a href="#3-dimensional" data-toc-modified-id="3-dimensional-2.1.3"><span class="toc-item-num">2.1.3&nbsp;&nbsp;</span>3 dimensional</a></span></li></ul></li><li><span><a href="#Built-in" data-toc-modified-id="Built-in-2.2"><span class="toc-item-num">2.2&nbsp;&nbsp;</span>Built-in</a></span><ul class="toc-item"><li><span><a href="#arange" data-toc-modified-id="arange-2.2.1"><span class="toc-item-num">2.2.1&nbsp;&nbsp;</span><code>arange</code></a></span></li><li><span><a href="#linspace" data-toc-modified-id="linspace-2.2.2"><span class="toc-item-num">2.2.2&nbsp;&nbsp;</span><code>linspace</code></a></span></li></ul></li></ul></li><li><span><a href="#Properties" data-toc-modified-id="Properties-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Properties</a></span></li><li><span><a href="#Slicing" data-toc-modified-id="Slicing-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>Slicing</a></span><ul class="toc-item"><li><span><a href="#Conditional-slicing" data-toc-modified-id="Conditional-slicing-4.1"><span class="toc-item-num">4.1&nbsp;&nbsp;</span>Conditional slicing</a></span></li></ul></li><li><span><a href="#Useful-array-methods" data-toc-modified-id="Useful-array-methods-5"><span class="toc-item-num">5&nbsp;&nbsp;</span>Useful array methods</a></span></li><li><span><a href="#Broadcasting" data-toc-modified-id="Broadcasting-6"><span class="toc-item-num">6&nbsp;&nbsp;</span>Broadcasting</a></span></li><li><span><a href="#Further-materials" data-toc-modified-id="Further-materials-7"><span class="toc-item-num">7&nbsp;&nbsp;</span>Further materials</a></span></li></ul></div>

In [1]:
import numpy as np

Convention for this notebook:
 - `a` will always be a 1-dimensional array.
 - `b` will always be a 2-dimensional array.
 - `c` will always be a 3-dimensional array.

## Why numpy

NumPy (numerical Python) is used to do numerical computations efficiently in Python

In [11]:
lst = [1, 2, 3, 4, 5]

In [12]:
type(lst)

list

I want to multiply all elements by `2`

In [13]:
lst * 2

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

Did not work

In [106]:
arr = np.array(lst)

In [15]:
arr

array([1, 2, 3, 4, 5])

In [16]:
type(arr)

numpy.ndarray

In [17]:
arr * 2

array([ 2,  4,  6,  8, 10])

As expected

Takes less time to do stuff, C programming language optimized

In [2]:
lst2 = list(range(1_000_000))

In [7]:
%%timeit
doubles = [n * 2 for n in lst2]

81.1 ms ± 367 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [8]:
arr2 = np.array(lst2)

In [9]:
%%timeit
doubles = arr2 * 2

1.22 ms ± 74.5 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


## Creating arrays

### Custom

#### 1 dimensional

In [25]:
a = np.array([1, 2, 3])

In [27]:
type(a)

numpy.ndarray

In [28]:
a

array([1, 2, 3])

In [31]:
a.shape

(3,)

#### 2 dimensional

In [32]:
b = np.array([[1, 2, 3], [4, 5, 6]])

In [33]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [34]:
b.shape

(2, 3)

Meaning 2 rows, 3 columns.

#### 3 dimensional

In [46]:
c = np.array([
    [[55, 66, 3], [40, 90, 3]],
    [[10, 10, 3], [10, 11, 3]],
    [[8, 9, 354], [6, 75, 34]],
    [[2, 3, 443], [3, 4, 199]]
])

In [47]:
c

array([[[ 55,  66,   3],
        [ 40,  90,   3]],

       [[ 10,  10,   3],
        [ 10,  11,   3]],

       [[  8,   9, 354],
        [  6,  75,  34]],

       [[  2,   3, 443],
        [  3,   4, 199]]])

In [48]:
c.shape

(4, 2, 3)

Example 3 dimensional arrays: RGB images

### Built-in

In [ ]:
np.zeros

In [ ]:
np.ones

In [ ]:
np.eye

In [ ]:
np.full

In [ ]:
np.empty

In [ ]:
np.random.random()

In [ ]:
np.random.randint(low=, high=, size=)

In [67]:
np.random.randn(10)

array([ 0.39902954, -1.21861519,  0.24762256,  0.14591193,  1.14566257,
        1.71556448,  0.26875249, -0.25608993, -1.15075792, -2.40470013])

#### `arange`

#### `linspace`

## Properties

In [109]:
b = np.random.randint(0, 100, (3, 4))

In [105]:
b

array([[65, 54, 56,  7],
       [56, 40, 38, 35],
       [35, 40, 78,  9]])

In [ ]:
b.shape

In [ ]:
b.size

In [ ]:
b.ndim

In [ ]:
b.dtype

## Slicing

In [110]:
b = np.random.randint(0, 100, (3, 4))

In [ ]:
b[0, 1]

In [ ]:
b[0, :]

In [ ]:
b[:, 0]

In [96]:
a = np.random.randint(0, 100, 20)

In [ ]:
a[0:10:3]

### Conditional slicing

In [96]:
a = np.random.randint(0, 100, 20)

In [97]:
a

array([95, 17, 45, 54, 65, 30, 19,  7, 68, 26, 15, 18, 88,  3, 51,  9, 34,
       86, 36, 49])

In [100]:
cond = (a > 10) & (a % 2 == 0)

In [ ]:
cond

In [100]:
a[cond]

## Useful array methods

In [ ]:
max
min
sum axis

mean
var
round

In [ ]:
flatten
reshape

In [ ]:
transpose
inverse

In [ ]:
+ 
*
** 2
np.exp

In [ ]:
==

In [117]:
b = np.random.randint(0, 10, (5, 5))

In [121]:
b2 = np.random.randint(0, 10, (5, 5))

In [122]:
b

array([[1, 7, 4, 5, 8],
       [4, 7, 5, 8, 2],
       [9, 2, 3, 5, 0],
       [6, 3, 8, 4, 6],
       [8, 2, 6, 8, 3]])

In [125]:
b2

array([[3, 0, 3, 4, 6],
       [9, 6, 5, 0, 9],
       [6, 8, 6, 7, 0],
       [5, 2, 4, 8, 9],
       [0, 1, 8, 3, 6]])

In [123]:
b == 3

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False,  True, False, False],
       [False,  True, False, False, False],
       [False, False, False, False,  True]])

In [124]:
b == b2

array([[False, False, False, False, False],
       [False, False,  True, False, False],
       [False, False, False, False,  True],
       [False, False, False, False, False],
       [False, False, False, False, False]])

## Broadcasting

## Further materials

[NumPy Cheatsheet](https://s3.amazonaws.com/assets.datacamp.com/blog_assets/Numpy_Python_Cheat_Sheet.pdf)