# Numpy

<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Why-numpy" data-toc-modified-id="Why-numpy-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Why numpy</a></span></li><li><span><a href="#Creating-arrays" data-toc-modified-id="Creating-arrays-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Creating arrays</a></span><ul class="toc-item"><li><span><a href="#Custom" data-toc-modified-id="Custom-2.1"><span class="toc-item-num">2.1&nbsp;&nbsp;</span>Custom</a></span><ul class="toc-item"><li><span><a href="#1-dimensional" data-toc-modified-id="1-dimensional-2.1.1"><span class="toc-item-num">2.1.1&nbsp;&nbsp;</span>1 dimensional</a></span></li><li><span><a href="#2-dimensional" data-toc-modified-id="2-dimensional-2.1.2"><span class="toc-item-num">2.1.2&nbsp;&nbsp;</span>2 dimensional</a></span></li><li><span><a href="#3-dimensional" data-toc-modified-id="3-dimensional-2.1.3"><span class="toc-item-num">2.1.3&nbsp;&nbsp;</span>3 dimensional</a></span></li></ul></li><li><span><a href="#Built-in" data-toc-modified-id="Built-in-2.2"><span class="toc-item-num">2.2&nbsp;&nbsp;</span>Built-in</a></span><ul class="toc-item"><li><span><a href="#arange" data-toc-modified-id="arange-2.2.1"><span class="toc-item-num">2.2.1&nbsp;&nbsp;</span><code>arange</code></a></span></li><li><span><a href="#linspace" data-toc-modified-id="linspace-2.2.2"><span class="toc-item-num">2.2.2&nbsp;&nbsp;</span><code>linspace</code></a></span></li></ul></li></ul></li><li><span><a href="#Properties" data-toc-modified-id="Properties-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Properties</a></span></li><li><span><a href="#Slicing" data-toc-modified-id="Slicing-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>Slicing</a></span><ul class="toc-item"><li><span><a href="#Conditional-slicing" data-toc-modified-id="Conditional-slicing-4.1"><span class="toc-item-num">4.1&nbsp;&nbsp;</span>Conditional slicing</a></span></li></ul></li><li><span><a href="#Useful-array-methods" data-toc-modified-id="Useful-array-methods-5"><span class="toc-item-num">5&nbsp;&nbsp;</span>Useful array methods</a></span></li><li><span><a href="#Broadcasting" data-toc-modified-id="Broadcasting-6"><span class="toc-item-num">6&nbsp;&nbsp;</span>Broadcasting</a></span></li><li><span><a href="#Further-materials" data-toc-modified-id="Further-materials-7"><span class="toc-item-num">7&nbsp;&nbsp;</span>Further materials</a></span></li></ul></div>

In [1]:
import numpy as np

Convention for this notebook:
 - `a` will always be a 1-dimensional array.
 - `b` will always be a 2-dimensional array.
 - `c` will always be a 3-dimensional array.

## Why numpy

NumPy (numerical Python) is used to do numerical computations efficiently in Python

In [2]:
lst = [1, 2, 3, 4, 5]

In [3]:
type(lst)

list

I want to multiply all elements by `2`

In [4]:
lst * 2

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

Did not work

`np.array` is the function

`arr` is the variable name. We are free to choose it

In [5]:
arr = np.array(lst)

In [14]:
type(arr)

numpy.ndarray

In [11]:
arr

array([1, 2, 3, 4, 5])

In [8]:
arr * 2

array([ 2,  4,  6,  8, 10])

As expected

In [12]:
arr * 1.5

array([1.5, 3. , 4.5, 6. , 7.5])

In [13]:
lst * 1.5

TypeError: can't multiply sequence by non-int of type 'float'

Takes less time to do stuff, C programming language optimized

In [23]:
lst2 = list(range(1_000_000))

In [24]:
type(lst2)

list

In [18]:
lst2[:20]

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

In [26]:
%%timeit
list(map(lambda x: x * 2, lst2))

220 ms ± 17.5 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [27]:
%%timeit
map(lambda x: x * 2, lst2)

314 ns ± 14.8 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [19]:
%%timeit
doubles = [n * 2 for n in lst2]

139 ms ± 4.61 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [20]:
arr2 = np.array(lst2)

In [21]:
type(arr2)

numpy.ndarray

In [22]:
%%timeit
doubles = arr2 * 2

5.23 ms ± 250 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


## Creating arrays

### Custom

#### 1 dimensional

In [28]:
a = np.array([1, 2, 3])

In [29]:
type(a)

numpy.ndarray

In [30]:
a

array([1, 2, 3])

In [31]:
a.shape

(3,)

#### 2 dimensional

In [32]:
b = np.array([[1, 2, 3], [4, 5, 6]])

In [33]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [34]:
b.shape

(2, 3)

Meaning 2 rows, 3 columns.

In [35]:
b2 = np.array([[1, 2, 3], [4, 5, 6, 7]])

<ipython-input-35-c25226e2f92c>:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  b2 = np.array([[1, 2, 3], [4, 5, 6, 7]])


In [37]:
b2

array([list([1, 2, 3]), list([4, 5, 6, 7])], dtype=object)

#### 3 dimensional

In [38]:
c = np.array([
    [[55, 66, 3], [40, 90, 3]],
    [[10, 10, 3], [10, 11, 3]],
    [[8, 9, 354], [6, 75, 34]],
    [[2, 3, 443], [3, 4, 199]]
])

In [39]:
c

array([[[ 55,  66,   3],
        [ 40,  90,   3]],

       [[ 10,  10,   3],
        [ 10,  11,   3]],

       [[  8,   9, 354],
        [  6,  75,  34]],

       [[  2,   3, 443],
        [  3,   4, 199]]])

In [40]:
c.shape

(4, 2, 3)

Example 3 dimensional arrays: RGB images

### Built-in

In [47]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [48]:
np.zeros((3, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [49]:
np.zeros((3, 5), dtype=int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [50]:
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [55]:
np.ones((2, 3)) * 4

array([[4., 4., 4.],
       [4., 4., 4.]])

In [57]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [58]:
np.full((2, 3), fill_value=4)

array([[4, 4, 4],
       [4, 4, 4]])

In [59]:
np.empty((2, 3))

array([[0.000000e+000, 4.940656e-324, 9.881313e-324],
       [4.940642e-318, 4.940647e-318, 4.940652e-318]])

In [78]:
np.random.random()

0.6187282404359425

In [88]:
np.random.randint(low=20, high=30, size=20)

array([21, 20, 29, 22, 22, 25, 29, 25, 22, 26, 22, 21, 29, 20, 22, 22, 20,
       21, 21, 28])

In [90]:
np.random.randint(low=20, high=30, size=(2, 3))

array([[28, 21, 27],
       [23, 23, 21]])

In [92]:
np.random.randn(10)

array([-1.38989645, -1.80784806,  0.15606463, -1.4482209 ,  0.44159914,
        0.06297022, -0.12431652,  0.32422525,  1.02175974, -0.84017494])

In [94]:
np.random.randn(3, 3)

array([[-1.10075257, -0.09387099,  0.13150362],
       [ 1.47608543,  0.87374059, -1.14398819],
       [ 0.13019423, -1.24348328,  1.61534735]])

#### `arange`

Similar to `range`

In [97]:
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

#### `linspace`

In [100]:
np.linspace(0, 1, 9)

array([0.   , 0.125, 0.25 , 0.375, 0.5  , 0.625, 0.75 , 0.875, 1.   ])

In [101]:
np.linspace(0, 1, 3)

array([0. , 0.5, 1. ])

## Properties

In [103]:
b = np.random.randint(0, 100, (3, 4))

In [105]:
b

array([[33,  7, 48, 51],
       [57, 30, 19, 72],
       [78,  7, 50,  8]])

In [106]:
b.shape

(3, 4)

In [112]:
b

array([[33,  7, 48, 51],
       [57, 30, 19, 72],
       [78,  7, 50,  8]])

In [107]:
b.size

12

In [108]:
b.ndim

2

In [109]:
c

array([[[ 55,  66,   3],
        [ 40,  90,   3]],

       [[ 10,  10,   3],
        [ 10,  11,   3]],

       [[  8,   9, 354],
        [  6,  75,  34]],

       [[  2,   3, 443],
        [  3,   4, 199]]])

In [110]:
c.ndim

3

In [111]:
b.dtype

dtype('int64')

## Slicing

In [110]:
b = np.random.randint(0, 100, (3, 4))

In [ ]:
b[0, 1]

In [ ]:
b[0, :]

In [ ]:
b[:, 0]

In [96]:
a = np.random.randint(0, 100, 20)

In [ ]:
a[0:10:3]

### Conditional slicing

In [96]:
a = np.random.randint(0, 100, 20)

In [97]:
a

array([95, 17, 45, 54, 65, 30, 19,  7, 68, 26, 15, 18, 88,  3, 51,  9, 34,
       86, 36, 49])

In [100]:
cond = (a > 10) & (a % 2 == 0)

In [ ]:
cond

In [100]:
a[cond]

## Useful array methods

In [ ]:
max
min
sum axis

mean
var
round

In [ ]:
flatten
reshape

In [ ]:
transpose
inverse

In [ ]:
+ 
*
** 2
np.exp

In [ ]:
==

In [117]:
b = np.random.randint(0, 10, (5, 5))

In [121]:
b2 = np.random.randint(0, 10, (5, 5))

In [122]:
b

array([[1, 7, 4, 5, 8],
       [4, 7, 5, 8, 2],
       [9, 2, 3, 5, 0],
       [6, 3, 8, 4, 6],
       [8, 2, 6, 8, 3]])

In [125]:
b2

array([[3, 0, 3, 4, 6],
       [9, 6, 5, 0, 9],
       [6, 8, 6, 7, 0],
       [5, 2, 4, 8, 9],
       [0, 1, 8, 3, 6]])

In [123]:
b == 3

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False,  True, False, False],
       [False,  True, False, False, False],
       [False, False, False, False,  True]])

In [124]:
b == b2

array([[False, False, False, False, False],
       [False, False,  True, False, False],
       [False, False, False, False,  True],
       [False, False, False, False, False],
       [False, False, False, False, False]])

## Broadcasting

## Further materials

[NumPy Cheatsheet](https://s3.amazonaws.com/assets.datacamp.com/blog_assets/Numpy_Python_Cheat_Sheet.pdf)